// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv7XuxvLBg5t8z723af4FpSQoNHjU8mjY',
    appId: '1:652023040535:web:752f1c8729c84f2f3b6a52',
    messagingSenderId: '652023040535',
    projectId: 'kalena-mart-f7f52',
    authDomain: 'kalena-mart-f7f52.firebaseapp.com',
    storageBucket: 'kalena-mart-f7f52.appspot.com',
    measurementId: 'G-3ZRLV9CV2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgV3LDU9Ljbxyfs9-f5FrCy01wJ1Ybrm4',
    appId: '1:652023040535:android:092b916dc2ae0f2f3b6a52',
    messagingSenderId: '652023040535',
    projectId: 'kalena-mart-f7f52',
    storageBucket: 'kalena-mart-f7f52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbikAMMHKTIazce0ZE9znentzHtUvgaC0',
    appId: '1:652023040535:ios:8e15db23ac3d315b3b6a52',
    messagingSenderId: '652023040535',
    projectId: 'kalena-mart-f7f52',
    storageBucket: 'kalena-mart-f7f52.appspot.com',
    iosBundleId: 'com.example.kalenaMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbikAMMHKTIazce0ZE9znentzHtUvgaC0',
    appId: '1:652023040535:ios:daaa1c8dfdb1d0913b6a52',
    messagingSenderId: '652023040535',
    projectId: 'kalena-mart-f7f52',
    storageBucket: 'kalena-mart-f7f52.appspot.com',
    iosBundleId: 'com.example.kalenaMart.RunnerTests',
  );
}
